import type { SkillsCompiledRule } from './skillsLock';

export const SKILLS_LOCK_COMPILER_VERSION = '1.0.0';

export type SkillsRuleTemplate = Omit<SkillsCompiledRule, 'sourceSkill' | 'sourcePath'>;

export type SkillsCompilerTemplate = {
  name: string;
  description: string;
  rules: ReadonlyArray<SkillsRuleTemplate>;
};

export const skillsCompilerTemplates: Record<string, SkillsCompilerTemplate> = {
  'ios-guidelines': {
    name: 'ios-guidelines',
    description: 'Curated enforcement mapping for iOS skill baseline.',
    rules: [
      {
        id: 'skills.ios.no-force-unwrap',
        description: 'Disallow force unwrap in production iOS code.',
        severity: 'ERROR',
        platform: 'ios',
        confidence: 'HIGH',
        locked: true,
      },
      {
        id: 'skills.ios.no-force-try',
        description: 'Disallow force try in production iOS code.',
        severity: 'ERROR',
        platform: 'ios',
        confidence: 'HIGH',
        locked: true,
      },
      {
        id: 'skills.ios.no-anyview',
        description: 'Disallow AnyView in production iOS code.',
        severity: 'ERROR',
        platform: 'ios',
        confidence: 'HIGH',
        locked: true,
      },
      {
        id: 'skills.ios.no-callback-style-outside-bridges',
        description: 'Disallow callback-style signatures outside approved iOS bridge layers.',
        severity: 'WARN',
        platform: 'ios',
        confidence: 'MEDIUM',
        stage: 'PRE_PUSH',
        locked: true,
      },
      {
        id: 'skills.ios.no-force-cast',
        description: 'Disallow force cast in production iOS code.',
        severity: 'ERROR',
        platform: 'ios',
        confidence: 'HIGH',
        locked: true,
      },
    ],
  },
  'ios-concurrency-guidelines': {
    name: 'ios-concurrency-guidelines',
    description:
      'Curated enforcement mapping for Swift Concurrency references (actors, isolation, Sendable, tasks).',
    rules: [
      {
        id: 'skills.ios.no-dispatchqueue',
        description: 'Avoid DispatchQueue in production iOS code; prefer structured concurrency.',
        severity: 'WARN',
        platform: 'ios',
        confidence: 'HIGH',
        stage: 'PRE_PUSH',
        locked: true,
      },
      {
        id: 'skills.ios.no-dispatchgroup',
        description: 'Avoid DispatchGroup in production iOS code; prefer TaskGroup.',
        severity: 'WARN',
        platform: 'ios',
        confidence: 'HIGH',
        stage: 'PRE_PUSH',
        locked: true,
      },
      {
        id: 'skills.ios.no-dispatchsemaphore',
        description: 'Avoid DispatchSemaphore in production iOS code.',
        severity: 'ERROR',
        platform: 'ios',
        confidence: 'HIGH',
        stage: 'PRE_PUSH',
        locked: true,
      },
      {
        id: 'skills.ios.no-operation-queue',
        description: 'Avoid OperationQueue in production iOS code unless explicitly justified.',
        severity: 'WARN',
        platform: 'ios',
        confidence: 'MEDIUM',
        stage: 'PRE_PUSH',
        locked: true,
      },
      {
        id: 'skills.ios.no-task-detached',
        description: 'Avoid Task.detached in production iOS code without strict isolation rationale.',
        severity: 'WARN',
        platform: 'ios',
        confidence: 'MEDIUM',
        stage: 'PRE_PUSH',
        locked: true,
      },
      {
        id: 'skills.ios.no-unchecked-sendable',
        description: 'Avoid @unchecked Sendable in production iOS code without strict safety invariant.',
        severity: 'ERROR',
        platform: 'ios',
        confidence: 'HIGH',
        stage: 'PRE_PUSH',
        locked: true,
      },
      {
        id: 'skills.ios.no-preconcurrency',
        description:
          'Avoid @preconcurrency in production iOS code without a documented safety invariant and a removal ticket.',
        severity: 'ERROR',
        platform: 'ios',
        confidence: 'HIGH',
        stage: 'PRE_PUSH',
        locked: true,
      },
      {
        id: 'skills.ios.no-nonisolated-unsafe',
        description:
          'Avoid nonisolated(unsafe) in production iOS code without a documented safety invariant and a removal ticket.',
        severity: 'ERROR',
        platform: 'ios',
        confidence: 'HIGH',
        stage: 'PRE_PUSH',
        locked: true,
      },
      {
        id: 'skills.ios.no-assume-isolated',
        description:
          'Avoid assumeIsolated in production iOS code; prefer explicit actor isolation or await MainActor.run.',
        severity: 'ERROR',
        platform: 'ios',
        confidence: 'HIGH',
        stage: 'PRE_PUSH',
        locked: true,
      },
    ],
  },
  'ios-swiftui-expert-guidelines': {
    name: 'ios-swiftui-expert-guidelines',
    description:
      'Curated enforcement mapping for SwiftUI expert references (state, modern APIs, performance).',
    rules: [
      {
        id: 'skills.ios.no-observable-object',
        description: 'Avoid ObservableObject in modern iOS code; prefer @Observable where available.',
        severity: 'WARN',
        platform: 'ios',
        confidence: 'MEDIUM',
        stage: 'PRE_PUSH',
        locked: true,
      },
      {
        id: 'skills.ios.no-legacy-swiftui-observable-wrapper',
        description:
          'Avoid @StateObject and @ObservedObject in modern SwiftUI code paths that can adopt @Observable with @State/@Bindable.',
        severity: 'WARN',
        platform: 'ios',
        confidence: 'MEDIUM',
        stage: 'PRE_PUSH',
        locked: true,
      },
      {
        id: 'skills.ios.no-passed-value-state-wrapper',
        description:
          'Avoid storing values injected from a parent as @State or @StateObject; prefer let, @Binding, or owned @State created locally.',
        severity: 'WARN',
        platform: 'ios',
        confidence: 'HIGH',
        stage: 'PRE_PUSH',
        locked: true,
      },
      {
        id: 'skills.ios.no-navigation-view',
        description: 'Avoid NavigationView in modern iOS code; prefer NavigationStack.',
        severity: 'WARN',
        platform: 'ios',
        confidence: 'HIGH',
        stage: 'PRE_PUSH',
        locked: true,
      },
      {
        id: 'skills.ios.no-foreground-color',
        description: 'Avoid foregroundColor in modern SwiftUI code; prefer foregroundStyle.',
        severity: 'WARN',
        platform: 'ios',
        confidence: 'HIGH',
        stage: 'PRE_PUSH',
        locked: true,
      },
      {
        id: 'skills.ios.no-corner-radius',
        description: 'Avoid cornerRadius in modern SwiftUI code; prefer clipShape(.rect(cornerRadius:)).',
        severity: 'WARN',
        platform: 'ios',
        confidence: 'HIGH',
        stage: 'PRE_PUSH',
        locked: true,
      },
      {
        id: 'skills.ios.no-tab-item',
        description: 'Avoid tabItem in modern SwiftUI code paths that can adopt the new Tab API.',
        severity: 'WARN',
        platform: 'ios',
        confidence: 'MEDIUM',
        stage: 'PRE_PUSH',
        locked: true,
      },
      {
        id: 'skills.ios.no-on-tap-gesture',
        description: 'Avoid onTapGesture for button-like interactions in production iOS code.',
        severity: 'WARN',
        platform: 'ios',
        confidence: 'MEDIUM',
        stage: 'PRE_PUSH',
        locked: true,
      },
      {
        id: 'skills.ios.no-string-format',
        description: 'Avoid String(format:) in SwiftUI presentation code; prefer modern formatting APIs.',
        severity: 'WARN',
        platform: 'ios',
        confidence: 'HIGH',
        stage: 'PRE_PUSH',
        locked: true,
      },
      {
        id: 'skills.ios.no-foreach-indices',
        description:
          'Avoid ForEach over .indices in dynamic SwiftUI content; prefer stable element identity or explicit stable IDs.',
        severity: 'WARN',
        platform: 'ios',
        confidence: 'HIGH',
        stage: 'PRE_PUSH',
        locked: true,
      },
      {
        id: 'skills.ios.no-contains-user-filter',
        description:
          'Avoid contains() in user-facing filter flows; prefer localizedStandardContains() for SwiftUI search text matching.',
        severity: 'WARN',
        platform: 'ios',
        confidence: 'MEDIUM',
        stage: 'PRE_PUSH',
        locked: true,
      },
      {
        id: 'skills.ios.no-geometryreader',
        description:
          'Avoid GeometryReader in modern SwiftUI layout code when containerRelativeFrame(), visualEffect(), or simpler layout APIs are enough.',
        severity: 'WARN',
        platform: 'ios',
        confidence: 'MEDIUM',
        stage: 'PRE_PUSH',
        locked: true,
      },
      {
        id: 'skills.ios.no-font-weight-bold',
        description: 'Avoid fontWeight(.bold) in SwiftUI text styling; prefer bold() for straightforward emphasis.',
        severity: 'WARN',
        platform: 'ios',
        confidence: 'HIGH',
        stage: 'PRE_PUSH',
        locked: true,
      },
      {
        id: 'skills.ios.no-scrollview-shows-indicators',
        description: 'Avoid ScrollView(showsIndicators: false) in SwiftUI code; prefer scrollIndicators(.hidden).',
        severity: 'WARN',
        platform: 'ios',
        confidence: 'HIGH',
        stage: 'PRE_PUSH',
        locked: true,
      },
      {
        id: 'skills.ios.no-sheet-is-presented',
        description: 'Avoid .sheet(isPresented:) in SwiftUI presentation flows; prefer .sheet(item:) when possible.',
        severity: 'WARN',
        platform: 'ios',
        confidence: 'MEDIUM',
        stage: 'PRE_PUSH',
        locked: true,
      },
      {
        id: 'skills.ios.no-legacy-onchange',
        description: 'Avoid legacy single-parameter onChange in modern SwiftUI code; prefer modern overloads.',
        severity: 'WARN',
        platform: 'ios',
        confidence: 'HIGH',
        stage: 'PRE_PUSH',
        locked: true,
      },
      {
        id: 'skills.ios.no-uiscreen-main-bounds',
        description: 'Avoid UIScreen.main.bounds in SwiftUI layout code; prefer relative layout APIs.',
        severity: 'WARN',
        platform: 'ios',
        confidence: 'HIGH',
        stage: 'PRE_PUSH',
        locked: true,
      },
    ],
  },
  'ios-swift-testing-guidelines': {
    name: 'ios-swift-testing-guidelines',
    description:
      'Curated enforcement mapping for Swift Testing adoption in iOS unit and integration tests.',
    rules: [
      {
        id: 'skills.ios.critical-test-quality',
        description:
          'Critical iOS test quality contract: Swift tests must be covered by modern testing rules and XCTest compatibility guards.',
        severity: 'ERROR',
        platform: 'ios',
        confidence: 'HIGH',
        stage: 'PRE_COMMIT',
        locked: true,
      },
      {
        id: 'skills.ios.prefer-swift-testing',
        description:
          'Prefer Swift Testing over XCTest-only unit and integration tests, including suites that can migrate to import Testing and @Test.',
        severity: 'WARN',
        platform: 'ios',
        confidence: 'MEDIUM',
        stage: 'PRE_PUSH',
        locked: true,
      },
      {
        id: 'skills.ios.no-xctassert',
        description: 'Avoid XCTest assertion macros in modern Swift tests; prefer #expect.',
        severity: 'WARN',
        platform: 'ios',
        confidence: 'HIGH',
        stage: 'PRE_PUSH',
        locked: true,
      },
      {
        id: 'skills.ios.no-xctunwrap',
        description: 'Avoid XCTUnwrap in modern Swift tests; prefer #require.',
        severity: 'WARN',
        platform: 'ios',
        confidence: 'HIGH',
        stage: 'PRE_PUSH',
        locked: true,
      },
      {
        id: 'skills.ios.no-wait-for-expectations',
        description: 'Avoid wait(for:) and waitForExpectations(timeout:) in async iOS tests; prefer await fulfillment(of:).',
        severity: 'WARN',
        platform: 'ios',
        confidence: 'HIGH',
        stage: 'PRE_PUSH',
        locked: true,
      },
      {
        id: 'skills.ios.no-legacy-expectation-description',
        description: 'Avoid expectation(description:) scaffolding without modern fulfillment or confirmation flow in iOS tests.',
        severity: 'WARN',
        platform: 'ios',
        confidence: 'MEDIUM',
        stage: 'PRE_PUSH',
        locked: true,
      },
      {
        id: 'skills.ios.no-mixed-testing-frameworks',
        description:
          'Avoid mixing XCTestCase suites with Swift Testing markers in the same iOS test file without explicit compatibility reason.',
        severity: 'WARN',
        platform: 'ios',
        confidence: 'HIGH',
        stage: 'PRE_PUSH',
        locked: true,
      },
    ],
  },
  'ios-core-data-guidelines': {
    name: 'ios-core-data-guidelines',
    description:
      'Curated enforcement mapping for Core Data boundaries across layers, contexts, and async APIs.',
    rules: [
      {
        id: 'skills.ios.no-nsmanagedobject-boundary',
        description:
          'Avoid NSManagedObject in shared function and property boundaries; prefer object IDs or mapped models.',
        severity: 'WARN',
        platform: 'ios',
        confidence: 'MEDIUM',
        stage: 'PRE_PUSH',
        locked: true,
      },
      {
        id: 'skills.ios.no-nsmanagedobject-async-boundary',
        description:
          'Avoid NSManagedObject in async function boundaries; prefer object IDs or mapped models.',
        severity: 'ERROR',
        platform: 'ios',
        confidence: 'HIGH',
        stage: 'PRE_PUSH',
        locked: true,
      },
      {
        id: 'skills.ios.no-core-data-layer-leak',
        description:
          'Keep Core Data orchestration inside infrastructure or repository layers; avoid Core Data APIs in application or presentation code.',
        severity: 'ERROR',
        platform: 'ios',
        confidence: 'HIGH',
        stage: 'PRE_PUSH',
        locked: true,
      },
      {
        id: 'skills.ios.no-nsmanagedobject-state-leak',
        description:
          'Avoid leaking context-scoped NSManagedObject instances into SwiftUI state or view models; prefer object IDs or mapped models.',
        severity: 'ERROR',
        platform: 'ios',
        confidence: 'HIGH',
        stage: 'PRE_PUSH',
        locked: true,
      },
    ],
  },
  'backend-guidelines': {
    name: 'backend-guidelines',
    description: 'Curated enforcement mapping for backend skill baseline.',
    rules: [
      {
        id: 'skills.backend.no-empty-catch',
        description: 'Disallow empty catch blocks in backend runtime code.',
        severity: 'CRITICAL',
        platform: 'backend',
        confidence: 'HIGH',
        locked: true,
      },
      {
        id: 'skills.backend.no-console-log',
        description: 'Disallow console.log in backend runtime code.',
        severity: 'ERROR',
        platform: 'backend',
        confidence: 'HIGH',
        stage: 'PRE_PUSH',
        locked: true,
      },
      {
        id: 'skills.backend.no-loggear-datos-sensibles-passwords-tokens-pii',
        description: 'No loggear datos sensibles - Passwords, tokens, PII',
        severity: 'ERROR',
        platform: 'backend',
        confidence: 'HIGH',
        stage: 'PRE_PUSH',
        locked: true,
      },
      {
        id: 'skills.backend.guideline.backend.winston-logger-estructurado-json-logs',
        description: 'Winston - Logger estructurado (JSON logs)',
        severity: 'WARN',
        platform: 'backend',
        confidence: 'MEDIUM',
        stage: 'PRE_PUSH',
        locked: true,
      },
      {
        id: 'skills.backend.guideline.backend.loggear-errores-con-contexto-completo',
        description: 'Loggear errores - Con contexto completo',
        severity: 'WARN',
        platform: 'backend',
        confidence: 'MEDIUM',
        stage: 'PRE_PUSH',
        locked: true,
      },
      {
        id: 'skills.backend.guideline.backend.correlation-ids-para-tracing-distribuido',
        description: 'Correlation IDs - Para tracing distribuido',
        severity: 'WARN',
        platform: 'backend',
        confidence: 'MEDIUM',
        stage: 'PRE_PUSH',
        locked: true,
      },
      {
        id: 'skills.backend.guideline.backend.me-tricas-prometheus-prom-client-para-me-tricas',
        description: 'Métricas Prometheus - prom-client para métricas',
        severity: 'WARN',
        platform: 'backend',
        confidence: 'MEDIUM',
        stage: 'PRE_PUSH',
        locked: true,
      },
      {
        id: 'skills.backend.password-hashing-bcrypt-con-salt-rounds-10',
        description: 'Password hashing - bcrypt con salt rounds >= 10',
        severity: 'ERROR',
        platform: 'backend',
        confidence: 'HIGH',
        stage: 'PRE_PUSH',
        locked: true,
      },
      {
        id: 'skills.backend.guideline.backend.rate-limiting-nestjs-throttler-para-prevenir-brute-force',
        description: 'Rate limiting - @nestjs/throttler para prevenir brute force',
        severity: 'WARN',
        platform: 'backend',
        confidence: 'MEDIUM',
        stage: 'PRE_PUSH',
        locked: true,
      },
      {
        id: 'skills.backend.guideline.backend.rate-limiting-throttler-para-prevenir-abuse',
        description: 'Rate limiting - Throttler para prevenir abuse',
        severity: 'WARN',
        platform: 'backend',
        confidence: 'MEDIUM',
        stage: 'PRE_PUSH',
        locked: true,
      },
      {
        id: 'skills.backend.guideline.backend.cors-configurado-solo-ori-genes-permitidos',
        description: 'CORS configurado - Solo orígenes permitidos',
        severity: 'WARN',
        platform: 'backend',
        confidence: 'MEDIUM',
        stage: 'PRE_PUSH',
        locked: true,
      },
      {
        id: 'skills.backend.guideline.backend.cors-configurar-ori-genes-permitidos',
        description: 'CORS - Configurar orígenes permitidos',
        severity: 'WARN',
        platform: 'backend',
        confidence: 'MEDIUM',
        stage: 'PRE_PUSH',
        locked: true,
      },
      {
        id: 'skills.backend.guideline.backend.pipes-para-validacio-n-global-validationpipe-en-main-ts',
        description: 'Pipes para validación global - ValidationPipe en main.ts',
        severity: 'WARN',
        platform: 'backend',
        confidence: 'MEDIUM',
        stage: 'PRE_PUSH',
        locked: true,
      },
      {
        id: 'skills.backend.guideline.backend.validationpipe-global-en-main-ts-con-whitelist-true',
        description: 'ValidationPipe global - En main.ts con whitelist: true',
        severity: 'WARN',
        platform: 'backend',
        confidence: 'MEDIUM',
        stage: 'PRE_PUSH',
        locked: true,
      },
      {
        id: 'skills.backend.guideline.backend.versionado-api-v1-api-v2',
        description: 'Versionado - /api/v1/, /api/v2/',
        severity: 'WARN',
        platform: 'backend',
        confidence: 'MEDIUM',
        stage: 'PRE_PUSH',
        locked: true,
      },
      {
        id: 'skills.backend.guideline.backend.validation-de-config-joi-o-class-validator-para-env',
        description: 'Validation de config - Joi o class-validator para .env',
        severity: 'WARN',
        platform: 'backend',
        confidence: 'MEDIUM',
        stage: 'PRE_PUSH',
        locked: true,
      },
      {
        id: 'skills.backend.guideline.backend.class-validator-decorators-isstring-isemail-min-max',
        description: 'class-validator decorators - @IsString(), @IsEmail(), @Min(), @Max()',
        severity: 'WARN',
        platform: 'backend',
        confidence: 'MEDIUM',
        stage: 'PRE_PUSH',
        locked: true,
      },
      {
        id: 'skills.backend.guideline.backend.class-transformer-transform-exclude-expose',
        description: 'class-transformer - @Transform(), @Exclude(), @Expose()',
        severity: 'WARN',
        platform: 'backend',
        confidence: 'MEDIUM',
        stage: 'PRE_PUSH',
        locked: true,
      },
      {
        id: 'skills.backend.guideline.backend.input-validation-siempre-validar-con-dtos',
        description: 'Input validation - SIEMPRE validar con DTOs',
        severity: 'WARN',
        platform: 'backend',
        confidence: 'MEDIUM',
        stage: 'PRE_PUSH',
        locked: true,
      },
      {
        id: 'skills.backend.guideline.backend.nested-validation-validatenested-type',
        description: 'Nested validation - @ValidateNested(), @Type()',
        severity: 'WARN',
        platform: 'backend',
        confidence: 'MEDIUM',
        stage: 'PRE_PUSH',
        locked: true,
      },
      {
        id: 'skills.backend.guideline.backend.dtos-en-boundaries-validacio-n-en-entrada-salida',
        description: 'DTOs en boundaries - Validación en entrada/salida',
        severity: 'WARN',
        platform: 'backend',
        confidence: 'MEDIUM',
        stage: 'PRE_PUSH',
        locked: true,
      },
      {
        id: 'skills.backend.guideline.backend.dtos-separados-createorderdto-updateorderdto-orderresponsedto',
        description: 'DTOs separados - CreateOrderDto, UpdateOrderDto, OrderResponseDto',
        severity: 'WARN',
        platform: 'backend',
        confidence: 'MEDIUM',
        stage: 'PRE_PUSH',
        locked: true,
      },
      {
        id: 'skills.backend.guideline.backend.retornar-dtos-no-exponer-entidades-directamente',
        description: 'Retornar DTOs - No exponer entidades directamente',
        severity: 'WARN',
        platform: 'backend',
        confidence: 'MEDIUM',
        stage: 'PRE_PUSH',
        locked: true,
      },
      {
        id: 'skills.backend.guideline.backend.transacciones-para-operaciones-cri-ticas',
        description: 'Transacciones - Para operaciones críticas',
        severity: 'WARN',
        platform: 'backend',
        confidence: 'MEDIUM',
        stage: 'PRE_PUSH',
        locked: true,
      },
      {
        id: 'skills.backend.guideline.backend.transacciones-para-operaciones-multi-tabla',
        description: 'Transacciones - Para operaciones multi-tabla',
        severity: 'WARN',
        platform: 'backend',
        confidence: 'MEDIUM',
        stage: 'PRE_PUSH',
        locked: true,
      },
      {
        id: 'skills.backend.mocks-en-produccio-n-solo-datos-reales',
        description: 'Disallow production mocks in backend runtime code; keep real data and real services in production.',
        severity: 'ERROR',
        platform: 'backend',
        confidence: 'HIGH',
        stage: 'PRE_PUSH',
        locked: true,
      },
      {
        id: 'skills.backend.exception-filters-catch-para-manejo-global',
        description: 'Disallow unmanaged exception filter handling in backend runtime code; centralize global exception handling.',
        severity: 'ERROR',
        platform: 'backend',
        confidence: 'HIGH',
        stage: 'PRE_PUSH',
        locked: true,
      },
      {
        id: 'skills.backend.guards-para-autenticacio-n-autorizacio-n-useguards-jwtauthguard',
        description: 'Require explicit guards for backend routes using UseGuards(JwtAuthGuard).',
        severity: 'ERROR',
        platform: 'backend',
        confidence: 'HIGH',
        stage: 'PRE_PUSH',
        locked: true,
      },
      {
        id: 'skills.backend.interceptors-para-logging-transformacio-n-no-en-cada-endpoint',
        description: 'Interceptors para logging/transformación - No en cada endpoint',
        severity: 'WARN',
        platform: 'backend',
        confidence: 'MEDIUM',
        stage: 'PRE_PUSH',
        locked: true,
      },
      {
        id: 'skills.backend.avoid-explicit-any',
        description: 'Avoid explicit any in backend runtime code.',
        severity: 'WARN',
        platform: 'backend',
        confidence: 'MEDIUM',
        stage: 'PRE_COMMIT',
        locked: true,
      },
      {
        id: 'skills.backend.no-solid-violations',
        description: 'Disallow backend SOLID violations in production code.',
        severity: 'ERROR',
        platform: 'backend',
        confidence: 'HIGH',
        stage: 'PRE_PUSH',
        locked: true,
      },
      {
        id: 'skills.backend.enforce-clean-architecture',
        description: 'Enforce clean architecture dependency direction in backend code.',
        severity: 'ERROR',
        platform: 'backend',
        confidence: 'HIGH',
        stage: 'PRE_PUSH',
        locked: true,
      },
      {
        id: 'skills.backend.no-singleton',
        description: 'Disallow singleton object patterns in backend code; use NestJS DI container.',
        severity: 'ERROR',
        platform: 'backend',
        confidence: 'HIGH',
        stage: 'PRE_PUSH',
        locked: true,
      },
      {
        id: 'skills.backend.magic-numbers-usar-constantes-con-nombres-descriptivos',
        description: 'Disallow magic numbers in backend code; use descriptive named constants.',
        severity: 'ERROR',
        platform: 'backend',
        confidence: 'HIGH',
        stage: 'PRE_PUSH',
        locked: true,
      },
      {
        id: 'skills.backend.hardcoded-values-config-en-variables-de-entorno',
        description: 'Disallow hardcoded config values in backend code; use environment variables.',
        severity: 'ERROR',
        platform: 'backend',
        confidence: 'HIGH',
        stage: 'PRE_PUSH',
        locked: true,
      },
      {
        id: 'skills.backend.no-defaults-en-produccio-n-fallar-si-falta-config-cri-tica',
        description: 'Fail when critical backend production config is missing; avoid silent defaults.',
        severity: 'ERROR',
        platform: 'backend',
        confidence: 'HIGH',
        stage: 'PRE_PUSH',
        locked: true,
      },
      {
        id: 'skills.backend.callback-hell-usar-async-await',
        description: 'Avoid callback hell in backend code; prefer async/await and linear flows.',
        severity: 'WARN',
        platform: 'backend',
        confidence: 'HIGH',
        stage: 'PRE_PUSH',
        locked: true,
      },
      {
        id: 'skills.backend.no-god-classes',
        description: 'Disallow god classes in backend code.',
        severity: 'ERROR',
        platform: 'backend',
        confidence: 'HIGH',
        stage: 'PRE_PUSH',
        locked: true,
      },
    ],
  },
  'frontend-guidelines': {
    name: 'frontend-guidelines',
    description: 'Curated enforcement mapping for frontend skill baseline.',
    rules: [
      {
        id: 'skills.frontend.no-console-log',
        description: 'Disallow console.log in frontend production code.',
        severity: 'ERROR',
        platform: 'frontend',
        confidence: 'HIGH',
        stage: 'PRE_PUSH',
        locked: true,
      },
      {
        id: 'skills.frontend.no-empty-catch',
        description: 'Disallow empty catch blocks in frontend runtime code.',
        severity: 'ERROR',
        platform: 'frontend',
        confidence: 'HIGH',
        stage: 'PRE_PUSH',
        locked: true,
      },
      {
        id: 'skills.frontend.avoid-explicit-any',
        description: 'Avoid explicit any in frontend runtime code.',
        severity: 'WARN',
        platform: 'frontend',
        confidence: 'MEDIUM',
        stage: 'PRE_COMMIT',
        locked: true,
      },
      {
        id: 'skills.frontend.no-solid-violations',
        description: 'Disallow frontend SOLID violations in production code.',
        severity: 'ERROR',
        platform: 'frontend',
        confidence: 'HIGH',
        stage: 'PRE_PUSH',
        locked: true,
      },
      {
        id: 'skills.frontend.enforce-clean-architecture',
        description: 'Enforce clean architecture dependency direction in frontend code.',
        severity: 'ERROR',
        platform: 'frontend',
        confidence: 'HIGH',
        stage: 'PRE_PUSH',
        locked: true,
      },
      {
        id: 'skills.frontend.no-singleton',
        description:
          'Disallow singleton object patterns in frontend code; use providers, context, or DI containers.',
        severity: 'ERROR',
        platform: 'frontend',
        confidence: 'HIGH',
        stage: 'PRE_PUSH',
        locked: true,
      },
      {
        id: 'skills.frontend.callback-hell-usar-async-await',
        description: 'Avoid callback hell in frontend code; prefer async/await and linear flows.',
        severity: 'WARN',
        platform: 'frontend',
        confidence: 'HIGH',
        stage: 'PRE_PUSH',
        locked: true,
      },
      {
        id: 'skills.frontend.no-class-components',
        description: 'Disallow React class components in frontend code; use functional components.',
        severity: 'ERROR',
        platform: 'frontend',
        confidence: 'HIGH',
        stage: 'PRE_PUSH',
        locked: true,
      },
      {
        id: 'skills.frontend.no-god-classes',
        description: 'Disallow god classes in frontend code.',
        severity: 'ERROR',
        platform: 'frontend',
        confidence: 'HIGH',
        stage: 'PRE_PUSH',
        locked: true,
      },
    ],
  },
  'android-guidelines': {
    name: 'android-guidelines',
    description: 'Curated enforcement mapping for Android skill baseline.',
    rules: [
      {
        id: 'skills.android.no-thread-sleep',
        description: 'Disallow Thread.sleep in Android production code.',
        severity: 'ERROR',
        platform: 'android',
        confidence: 'HIGH',
        stage: 'PRE_PUSH',
        locked: true,
      },
      {
        id: 'skills.android.no-globalscope',
        description: 'Disallow GlobalScope in Android production code.',
        severity: 'ERROR',
        platform: 'android',
        confidence: 'HIGH',
        stage: 'PRE_PUSH',
        locked: true,
      },
      {
        id: 'skills.android.no-console-log',
        description: 'Disallow logs in Android production code.',
        severity: 'ERROR',
        platform: 'android',
        confidence: 'HIGH',
        stage: 'PRE_PUSH',
        locked: true,
      },
      {
        id: 'skills.android.guideline.android.timber-logging-library',
        description: 'Timber - Logging library',
        severity: 'WARN',
        platform: 'android',
        confidence: 'MEDIUM',
        stage: 'PRE_PUSH',
        locked: true,
      },
      {
        id: 'skills.android.guideline.android.analytics-firebase-analytics-o-custom',
        description: 'Analytics - Firebase Analytics o custom',
        severity: 'WARN',
        platform: 'android',
        confidence: 'MEDIUM',
        stage: 'PRE_PUSH',
        locked: true,
      },
      {
        id: 'skills.android.guideline.android.android-profiler-cpu-memory-network-profiling',
        description: 'Android Profiler - CPU, Memory, Network profiling',
        severity: 'WARN',
        platform: 'android',
        confidence: 'MEDIUM',
        stage: 'PRE_PUSH',
        locked: true,
      },
      {
        id: 'skills.android.guideline.android.touch-targets-mi-nimo-48dp',
        description: 'Touch targets - mínimo 48dp',
        severity: 'WARN',
        platform: 'android',
        confidence: 'MEDIUM',
        stage: 'PRE_PUSH',
        locked: true,
      },
      {
        id: 'skills.android.guideline.android.buildconfig-constantes-en-tiempo-de-compilacio-n',
        description: 'BuildConfig - Constantes en tiempo de compilación',
        severity: 'WARN',
        platform: 'android',
        confidence: 'MEDIUM',
        stage: 'PRE_PUSH',
        locked: true,
      },
      {
        id: 'skills.android.hardcoded-strings-usar-strings-xml',
        description: 'Disallow hardcoded strings in Android production code.',
        severity: 'ERROR',
        platform: 'android',
        confidence: 'HIGH',
        stage: 'PRE_PUSH',
        locked: true,
      },
      {
        id: 'skills.android.guideline.android.localization-strings-xml-por-idioma-values-es-values-en',
        description: 'strings.xml - Por idioma (values-es, values-en)',
        severity: 'WARN',
        platform: 'android',
        confidence: 'MEDIUM',
        stage: 'PRE_PUSH',
        locked: true,
      },
      {
        id: 'skills.android.guideline.android.plurals-values-plurals-xml',
        description: 'Plurals - values/plurals.xml',
        severity: 'WARN',
        platform: 'android',
        confidence: 'MEDIUM',
        stage: 'PRE_PUSH',
        locked: true,
      },
      {
        id: 'skills.android.no-singleton-usar-inyeccio-n-de-dependencias-hilt-dagger',
        description: 'Disallow singleton object patterns in Android production code; use Hilt or Dagger DI.',
        severity: 'ERROR',
        platform: 'android',
        confidence: 'HIGH',
        stage: 'PRE_PUSH',
        locked: true,
      },
      {
        id: 'skills.android.guideline.android.hilt-com-google-dagger-hilt-android',
        description: 'Hilt - com.google.dagger:hilt-android',
        severity: 'WARN',
        platform: 'android',
        confidence: 'MEDIUM',
        stage: 'PRE_PUSH',
        locked: true,
      },
      {
        id: 'skills.android.guideline.android.hilt-di-framework-no-manual-factories',
        description: 'Hilt - DI framework (NO manual factories)',
        severity: 'WARN',
        platform: 'android',
        confidence: 'MEDIUM',
        stage: 'PRE_PUSH',
        locked: true,
      },
      {
        id: 'skills.android.guideline.android.hiltandroidapp-application-class',
        description: '@HiltAndroidApp - Application class',
        severity: 'WARN',
        platform: 'android',
        confidence: 'MEDIUM',
        stage: 'PRE_PUSH',
        locked: true,
      },
      {
        id: 'skills.android.guideline.android.androidentrypoint-activity-fragment-viewmodel',
        description: '@AndroidEntryPoint - Activity, Fragment, ViewModel',
        severity: 'WARN',
        platform: 'android',
        confidence: 'MEDIUM',
        stage: 'PRE_PUSH',
        locked: true,
      },
      {
        id: 'skills.android.guideline.android.viewmodel-androidx-lifecycle-viewmodel',
        description: 'ViewModel - AndroidX Lifecycle ViewModel',
        severity: 'WARN',
        platform: 'android',
        confidence: 'MEDIUM',
        stage: 'PRE_PUSH',
        locked: true,
      },
      {
        id: 'skills.android.guideline.android.viewmodel-sobrevive-configuration-changes',
        description: 'ViewModel - Sobrevive cambios de configuración',
        severity: 'WARN',
        platform: 'android',
        confidence: 'MEDIUM',
        stage: 'PRE_PUSH',
        locked: true,
      },
      {
        id: 'skills.android.guideline.android.inject-constructor-constructor-injection',
        description: '@Inject constructor - Constructor injection',
        severity: 'WARN',
        platform: 'android',
        confidence: 'MEDIUM',
        stage: 'PRE_PUSH',
        locked: true,
      },
      {
        id: 'skills.android.guideline.android.module-installin-provide-dependencies',
        description: '@Module + @InstallIn - Provide dependencies',
        severity: 'WARN',
        platform: 'android',
        confidence: 'MEDIUM',
        stage: 'PRE_PUSH',
        locked: true,
      },
      {
        id: 'skills.android.guideline.android.binds-para-implementaciones-de-interfaces-ma-s-eficiente',
        description: '@Binds - Para implementaciones de interfaces (más eficiente)',
        severity: 'WARN',
        platform: 'android',
        confidence: 'MEDIUM',
        stage: 'PRE_PUSH',
        locked: true,
      },
      {
        id: 'skills.android.guideline.android.provides-para-interfaces-o-third-party',
        description: '@Provides - Para interfaces o third-party',
        severity: 'WARN',
        platform: 'android',
        confidence: 'MEDIUM',
        stage: 'PRE_PUSH',
        locked: true,
      },
      {
        id: 'skills.android.guideline.android.workmanager-androidx-work-work-runtime-ktx',
        description: 'WorkManager - androidx.work:work-runtime-ktx',
        severity: 'WARN',
        platform: 'android',
        confidence: 'MEDIUM',
        stage: 'PRE_PUSH',
        locked: true,
      },
      {
        id: 'skills.android.guideline.android.version-catalogs-libs-versions-toml-para-dependencias',
        description: 'Version catalogs - libs.versions.toml para dependencias',
        severity: 'WARN',
        platform: 'android',
        confidence: 'MEDIUM',
        stage: 'PRE_PUSH',
        locked: true,
      },
      {
        id: 'skills.android.guideline.android.workmanager-background-tasks',
        description: 'WorkManager - Background tasks',
        severity: 'WARN',
        platform: 'android',
        confidence: 'MEDIUM',
        stage: 'PRE_PUSH',
        locked: true,
      },
      {
        id: 'skills.android.guideline.android.androidtest-instrumented-tests-device-emulator',
        description: 'androidTest - Instrumented tests (Device/Emulator)',
        severity: 'WARN',
        platform: 'android',
        confidence: 'MEDIUM',
        stage: 'PRE_PUSH',
        locked: true,
      },
      {
        id: 'skills.android.guideline.android.aaa-pattern-arrange-act-assert',
        description: 'AAA pattern - Arrange, Act, Assert',
        severity: 'WARN',
        platform: 'android',
        confidence: 'MEDIUM',
        stage: 'PRE_PUSH',
        locked: true,
      },
      {
        id: 'skills.android.guideline.android.given-when-then-bdd-style',
        description: 'Given-When-Then - BDD style',
        severity: 'WARN',
        platform: 'android',
        confidence: 'MEDIUM',
        stage: 'PRE_PUSH',
        locked: true,
      },
      {
        id: 'skills.android.guideline.android.test-unit-tests-jvm',
        description: 'test/ - Unit tests (JVM)',
        severity: 'WARN',
        platform: 'android',
        confidence: 'MEDIUM',
        stage: 'PRE_PUSH',
        locked: true,
      },
      {
        id: 'skills.android.guideline.android.viewmodelscope-scope-de-viewmodel-cancelado-automa-ticamente',
        description: 'viewModelScope - Scope de ViewModel, cancelado automáticamente',
        severity: 'WARN',
        platform: 'android',
        confidence: 'MEDIUM',
        stage: 'PRE_PUSH',
        locked: true,
      },
      {
        id: 'skills.android.guideline.android.viewmodelscoped-para-dependencias-de-viewmodel',
        description: '@ViewModelScoped - Para dependencias de ViewModel',
        severity: 'WARN',
        platform: 'android',
        confidence: 'MEDIUM',
        stage: 'PRE_PUSH',
        locked: true,
      },
      {
        id: 'skills.android.guideline.android.composable-functions-composable-para-ui',
        description: 'Composable functions - @Composable para UI',
        severity: 'WARN',
        platform: 'android',
        confidence: 'MEDIUM',
        stage: 'PRE_PUSH',
        locked: true,
      },
      {
        id: 'skills.android.guideline.android.arguments-pasar-datos-entre-pantallas',
        description: 'Arguments - Pasar datos entre pantallas',
        severity: 'WARN',
        platform: 'android',
        confidence: 'MEDIUM',
        stage: 'PRE_PUSH',
        locked: true,
      },
      {
        id: 'skills.android.guideline.android.adaptive-layouts-responsive-design-windowsizeclass',
        description: 'Adaptive layouts - Responsive design (WindowSizeClass)',
        severity: 'WARN',
        platform: 'android',
        confidence: 'MEDIUM',
        stage: 'PRE_PUSH',
        locked: true,
      },
      {
        id: 'skills.android.guideline.android.analizar-estructura-existente-mo-dulos-interfaces-dependencias-gradle',
        description: 'Analizar estructura existente - Módulos, interfaces, dependencias, Gradle',
        severity: 'WARN',
        platform: 'android',
        confidence: 'MEDIUM',
        stage: 'PRE_PUSH',
        locked: true,
      },
      {
        id: 'skills.android.guideline.android.theme-color-scheme-typography-shapes',
        description: 'Theme - Color scheme, typography, shapes',
        severity: 'WARN',
        platform: 'android',
        confidence: 'MEDIUM',
        stage: 'PRE_PUSH',
        locked: true,
      },
      {
        id: 'skills.android.guideline.android.dark-theme-soportar-desde-di-a-1-issystemindarktheme',
        description: 'Dark theme - Soportar desde día 1 (isSystemInDarkTheme())',
        severity: 'WARN',
        platform: 'android',
        confidence: 'MEDIUM',
        stage: 'PRE_PUSH',
        locked: true,
      },
      {
        id: 'skills.android.guideline.android.accessibility-semantics-contentdescription',
        description: 'Accessibility - semantics, contentDescription',
        severity: 'WARN',
        platform: 'android',
        confidence: 'MEDIUM',
        stage: 'PRE_PUSH',
        locked: true,
      },
      {
        id: 'skills.android.guideline.android.contentdescription-para-ima-genes-y-botones',
        description: 'contentDescription - Para imágenes y botones',
        severity: 'WARN',
        platform: 'android',
        confidence: 'MEDIUM',
        stage: 'PRE_PUSH',
        locked: true,
      },
      {
        id: 'skills.android.guideline.android.talkback-screen-reader-de-android',
        description: 'TalkBack - Screen reader de Android',
        severity: 'WARN',
        platform: 'android',
        confidence: 'MEDIUM',
        stage: 'PRE_PUSH',
        locked: true,
      },
      {
        id: 'skills.android.guideline.android.text-scaling-soportar-font-scaling-del-sistema',
        description: 'Text scaling - Soportar font scaling del sistema',
        severity: 'WARN',
        platform: 'android',
        confidence: 'MEDIUM',
        stage: 'PRE_PUSH',
        locked: true,
      },
      {
        id: 'skills.android.guideline.android.god-activities-single-activity-composables',
        description: 'God Activities - Single Activity + Composables',
        severity: 'ERROR',
        platform: 'android',
        confidence: 'HIGH',
        stage: 'PRE_PUSH',
        locked: true,
      },
      {
        id: 'skills.android.guideline.android.single-activity-mu-ltiples-composables-fragments-no-activities',
        description: 'Single Activity - Múltiples Composables/Fragments, no Activities',
        severity: 'WARN',
        platform: 'android',
        confidence: 'MEDIUM',
        stage: 'PRE_PUSH',
        locked: true,
      },
      {
        id: 'skills.android.no-runblocking',
        description: 'Disallow runBlocking in Android production code.',
        severity: 'WARN',
        platform: 'android',
        confidence: 'MEDIUM',
        stage: 'PRE_COMMIT',
        locked: true,
      },
      {
        id: 'skills.android.guideline.android.coroutines-async-await-no-callbacks',
        description: 'Coroutines - async/await, NO callbacks',
        severity: 'WARN',
        platform: 'android',
        confidence: 'MEDIUM',
        stage: 'PRE_PUSH',
        locked: true,
      },
      {
        id: 'skills.android.guideline.android.async-await-paralelismo',
        description: 'async/await - Paralelismo',
        severity: 'WARN',
        platform: 'android',
        confidence: 'MEDIUM',
        stage: 'PRE_PUSH',
        locked: true,
      },
      {
        id: 'skills.android.guideline.android.supervisorscope-errores-no-cancelan-otros-jobs',
        description: 'supervisorScope - Errores no cancelan otros jobs',
        severity: 'WARN',
        platform: 'android',
        confidence: 'MEDIUM',
        stage: 'PRE_PUSH',
        locked: true,
      },
      {
        id: 'skills.android.guideline.android.suspend-functions-en-api-service',
        description: 'suspend functions - En API service',
        severity: 'WARN',
        platform: 'android',
        confidence: 'MEDIUM',
        stage: 'PRE_PUSH',
        locked: true,
      },
      {
        id: 'skills.android.guideline.android.suspend-functions-para-operaciones-async',
        description: 'suspend functions - Para operaciones async',
        severity: 'WARN',
        platform: 'android',
        confidence: 'MEDIUM',
        stage: 'PRE_PUSH',
        locked: true,
      },
      {
        id: 'skills.android.guideline.android.dao-data-access-objects-con-suspend-functions',
        description: '@Dao - Data Access Objects con suspend functions',
        severity: 'WARN',
        platform: 'android',
        confidence: 'MEDIUM',
        stage: 'PRE_PUSH',
        locked: true,
      },
      {
        id: 'skills.android.guideline.android.transaction-para-operaciones-multi-query',
        description: '@Transaction - Para operaciones multi-query',
        severity: 'WARN',
        platform: 'android',
        confidence: 'MEDIUM',
        stage: 'PRE_PUSH',
        locked: true,
      },
      {
        id: 'skills.android.guideline.android.stateflow-estado-mutable-observable',
        description: 'StateFlow - Estado mutable observable',
        severity: 'WARN',
        platform: 'android',
        confidence: 'MEDIUM',
        stage: 'PRE_PUSH',
        locked: true,
      },
      {
        id: 'skills.android.guideline.android.sharedflow-hot-stream-puede-no-tener-valor-para-eventos',
        description: 'SharedFlow - Hot stream, puede no tener valor, para eventos',
        severity: 'WARN',
        platform: 'android',
        confidence: 'MEDIUM',
        stage: 'PRE_PUSH',
        locked: true,
      },
      {
        id: 'skills.android.guideline.android.flow-builders-flow-emit-flowof-asflow',
        description: 'Flow builders - flow { emit() }, flowOf(), asFlow()',
        severity: 'WARN',
        platform: 'android',
        confidence: 'MEDIUM',
        stage: 'PRE_PUSH',
        locked: true,
      },
      {
        id: 'skills.android.guideline.android.collect-terminal-operator-para-consumir-flow',
        description: 'collect - Terminal operator para consumir Flow',
        severity: 'WARN',
        platform: 'android',
        confidence: 'MEDIUM',
        stage: 'PRE_PUSH',
        locked: true,
      },
      {
        id: 'skills.android.guideline.android.collect-as-state-consumir-flow-en-compose',
        description: 'collectAsState - Consumir Flow en Compose',
        severity: 'WARN',
        platform: 'android',
        confidence: 'MEDIUM',
        stage: 'PRE_PUSH',
        locked: true,
      },
      {
        id: 'skills.android.guideline.android.remember-evitar-recrear-objetos',
        description: 'remember - Evitar recrear objetos',
        severity: 'WARN',
        platform: 'android',
        confidence: 'MEDIUM',
        stage: 'PRE_PUSH',
        locked: true,
      },
      {
        id: 'skills.android.guideline.android.remember-para-mantener-estado-entre-recomposiciones',
        description: 'remember - Para mantener estado entre recomposiciones',
        severity: 'WARN',
        platform: 'android',
        confidence: 'MEDIUM',
        stage: 'PRE_PUSH',
        locked: true,
      },
      {
        id: 'skills.android.guideline.android.derivedstateof-ca-lculos-caros-solo-cuando-cambia-input',
        description: 'derivedStateOf - Cálculos caros solo cuando cambia input',
        severity: 'WARN',
        platform: 'android',
        confidence: 'MEDIUM',
        stage: 'PRE_PUSH',
        locked: true,
      },
      {
        id: 'skills.android.guideline.android.derivedstateof-ca-lculos-derivados-de-state',
        description: 'derivedStateOf - Cálculos derivados de state',
        severity: 'WARN',
        platform: 'android',
        confidence: 'MEDIUM',
        stage: 'PRE_PUSH',
        locked: true,
      },
      {
        id: 'skills.android.guideline.android.launchedeffect-side-effects-con-lifecycle',
        description: 'LaunchedEffect - Side effects con lifecycle',
        severity: 'WARN',
        platform: 'android',
        confidence: 'MEDIUM',
        stage: 'PRE_PUSH',
        locked: true,
      },
      {
        id: 'skills.android.guideline.android.launchedeffect-keys-controlar-cuando-se-relanza-effect',
        description: 'LaunchedEffect keys - Controlar cuándo se relanza effect',
        severity: 'WARN',
        platform: 'android',
        confidence: 'MEDIUM',
        stage: 'PRE_PUSH',
        locked: true,
      },
      {
        id: 'skills.android.guideline.android.disposableeffect-cleanup-cuando-composable-sale-de-composicio-n',
        description: 'DisposableEffect - Cleanup cuando Composable sale de composición',
        severity: 'WARN',
        platform: 'android',
        confidence: 'MEDIUM',
        stage: 'PRE_PUSH',
        locked: true,
      },
      {
        id: 'skills.android.guideline.android.preview-preview-para-ver-ui-sin-correr-app',
        description: 'Preview - @Preview para ver UI sin correr app',
        severity: 'WARN',
        platform: 'android',
        confidence: 'MEDIUM',
        stage: 'PRE_PUSH',
        locked: true,
      },
      {
        id: 'skills.android.guideline.android.recomposition-composables-deben-ser-idempotentes',
        description: 'Recomposition - Composables deben ser idempotentes',
        severity: 'WARN',
        platform: 'android',
        confidence: 'MEDIUM',
        stage: 'PRE_PUSH',
        locked: true,
      },
      {
        id: 'skills.android.guideline.android.uistate-sealed-class-loading-success-error-states',
        description: 'UiState sealed class - Loading, Success, Error states',
        severity: 'WARN',
        platform: 'android',
        confidence: 'MEDIUM',
        stage: 'PRE_PUSH',
        locked: true,
      },
      {
        id: 'skills.android.guideline.android.use-cases-lo-gica-de-negocio-encapsulada',
        description: 'Use Cases - Lógica de negocio encapsulada',
        severity: 'WARN',
        platform: 'android',
        confidence: 'MEDIUM',
        stage: 'PRE_PUSH',
        locked: true,
      },
      {
        id: 'skills.android.guideline.android.repository-pattern-abstraer-acceso-a-datos',
        description: 'Repository pattern - Abstraer acceso a datos',
        severity: 'WARN',
        platform: 'android',
        confidence: 'MEDIUM',
        stage: 'PRE_PUSH',
        locked: true,
      },
      {
        id: 'skills.android.guideline.android.repository-pattern-ordersrep',
        description: 'Repository pattern - OrdersRep',
        severity: 'WARN',
        platform: 'android',
        confidence: 'MEDIUM',
        stage: 'PRE_PUSH',
        locked: true,
      },
      {
        id: 'skills.android.guideline.android.app-startup-androidx-startup-para-lazy-init',
        description: 'App startup - androidx.startup para lazy init',
        severity: 'WARN',
        platform: 'android',
        confidence: 'MEDIUM',
        stage: 'PRE_PUSH',
        locked: true,
      },
      {
        id: 'skills.android.guideline.android.baseline-profiles-optimizacio-n-de-startup',
        description: 'Baseline Profiles - Optimización de startup',
        severity: 'WARN',
        platform: 'android',
        confidence: 'MEDIUM',
        stage: 'PRE_PUSH',
        locked: true,
      },
      {
        id: 'skills.android.guideline.android.single-source-of-truth-viewmodel-es-la-fuente',
        description: 'Single source of truth - ViewModel es la fuente',
        severity: 'WARN',
        platform: 'android',
        confidence: 'MEDIUM',
        stage: 'PRE_PUSH',
        locked: true,
      },
      {
        id: 'skills.android.guideline.android.skip-recomposition-para-metros-inmutables-o-estables',
        description: 'Skip recomposition - Parámetros inmutables o estables',
        severity: 'WARN',
        platform: 'android',
        confidence: 'MEDIUM',
        stage: 'PRE_PUSH',
        locked: true,
      },
      {
        id: 'skills.android.guideline.android.stability-composables-estables-recomponen-menos',
        description: 'Stability - Composables estables recomponen menos',
        severity: 'WARN',
        platform: 'android',
        confidence: 'MEDIUM',
        stage: 'PRE_PUSH',
        locked: true,
      },
      {
        id: 'skills.android.guideline.android.string-formatting-1-s-2-d-para-argumentos',
        description: 'String formatting - %1$s, %2$d para argumentos',
        severity: 'WARN',
        platform: 'android',
        confidence: 'MEDIUM',
        stage: 'PRE_PUSH',
        locked: true,
      },
      {
        id: 'skills.android.guideline.android.state-hoisting-elevar-estado-al-nivel-apropiado',
        description: 'State hoisting - Elevar estado al nivel apropiado',
        severity: 'WARN',
        platform: 'android',
        confidence: 'MEDIUM',
        stage: 'PRE_PUSH',
        locked: true,
      },
    ],
  },
};
