import assert from 'node:assert/strict';
import test from 'node:test';
import { iosRules } from './ios';

test('iosRules define reglas heurísticas locked para plataforma ios', () => {
  assert.equal(iosRules.length, 58);

  const ids = iosRules.map((rule) => rule.id);
  assert.deepEqual(ids, [
    'heuristics.ios.force-unwrap.ast',
    'heuristics.ios.anyview.ast',
    'heuristics.ios.force-try.ast',
    'heuristics.ios.force-cast.ast',
    'heuristics.ios.callback-style.ast',
    'heuristics.ios.dispatchqueue.ast',
    'heuristics.ios.dispatchgroup.ast',
    'heuristics.ios.dispatchsemaphore.ast',
    'heuristics.ios.operation-queue.ast',
    'heuristics.ios.task-detached.ast',
    'heuristics.ios.logging.adhoc-print.ast',
    'heuristics.ios.logging.sensitive-data.ast',
    'heuristics.ios.networking.alamofire.ast',
    'heuristics.ios.json.jsonserialization.ast',
    'heuristics.ios.dependencies.cocoapods.ast',
    'heuristics.ios.dependencies.carthage.ast',
    'heuristics.ios.security.userdefaults-sensitive-data.ast',
    'heuristics.ios.security.insecure-transport.ast',
    'heuristics.ios.localization.localizable-strings.ast',
    'heuristics.ios.localization.hardcoded-ui-string.ast',
    'heuristics.ios.assets.loose-resource.ast',
    'heuristics.ios.accessibility.fixed-font-size.ast',
    'heuristics.ios.localization.physical-text-alignment.ast',
    'heuristics.ios.performance.blocking-sleep.ast',
    'heuristics.ios.accessibility.icon-only-control-label.ast',
    'heuristics.ios.unchecked-sendable.ast',
    'heuristics.ios.preconcurrency.ast',
    'heuristics.ios.nonisolated-unsafe.ast',
    'heuristics.ios.assume-isolated.ast',
    'heuristics.ios.observable-object.ast',
    'heuristics.ios.legacy-swiftui-observable-wrapper.ast',
    'heuristics.ios.passed-value-state-wrapper.ast',
    'heuristics.ios.foreach-indices.ast',
    'heuristics.ios.contains-user-filter.ast',
    'heuristics.ios.geometryreader.ast',
    'heuristics.ios.font-weight-bold.ast',
    'heuristics.ios.navigation-view.ast',
    'heuristics.ios.foreground-color.ast',
    'heuristics.ios.corner-radius.ast',
    'heuristics.ios.tab-item.ast',
    'heuristics.ios.on-tap-gesture.ast',
    'heuristics.ios.string-format.ast',
    'heuristics.ios.scrollview-shows-indicators.ast',
    'heuristics.ios.sheet-is-presented.ast',
    'heuristics.ios.legacy-onchange.ast',
    'heuristics.ios.uiscreen-main-bounds.ast',
    'heuristics.ios.testing.xctest-import.ast',
    'heuristics.ios.testing.xctest-suite-modernizable.ast',
    'heuristics.ios.testing.xctassert.ast',
    'heuristics.ios.testing.xctunwrap.ast',
    'heuristics.ios.testing.wait-for-expectations.ast',
    'heuristics.ios.testing.legacy-expectation-description.ast',
    'heuristics.ios.testing.mixed-frameworks.ast',
    'heuristics.ios.core-data.nsmanagedobject-boundary.ast',
    'heuristics.ios.core-data.nsmanagedobject-async-boundary.ast',
    'heuristics.ios.core-data.layer-leak.ast',
    'heuristics.ios.swiftdata.layer-leak.ast',
    'heuristics.ios.core-data.nsmanagedobject-state-leak.ast',
  ]);

  const byId = new Map(iosRules.map((rule) => [rule.id, rule]));
  assert.equal(
    byId.get('heuristics.ios.force-unwrap.ast')?.then.code,
    'HEURISTICS_IOS_FORCE_UNWRAP_AST'
  );
  assert.equal(
    byId.get('heuristics.ios.task-detached.ast')?.then.code,
    'HEURISTICS_IOS_TASK_DETACHED_AST'
  );
  assert.equal(
    byId.get('heuristics.ios.logging.adhoc-print.ast')?.then.code,
    'HEURISTICS_IOS_LOGGING_ADHOC_PRINT_AST'
  );
  assert.equal(
    byId.get('heuristics.ios.logging.sensitive-data.ast')?.then.code,
    'HEURISTICS_IOS_LOGGING_SENSITIVE_DATA_AST'
  );
  assert.equal(
    byId.get('heuristics.ios.networking.alamofire.ast')?.then.code,
    'HEURISTICS_IOS_NETWORKING_ALAMOFIRE_AST'
  );
  assert.equal(
    byId.get('heuristics.ios.json.jsonserialization.ast')?.then.code,
    'HEURISTICS_IOS_JSON_JSONSERIALIZATION_AST'
  );
  assert.equal(
    byId.get('heuristics.ios.dependencies.cocoapods.ast')?.then.code,
    'HEURISTICS_IOS_DEPENDENCIES_COCOAPODS_AST'
  );
  assert.equal(
    byId.get('heuristics.ios.dependencies.carthage.ast')?.then.code,
    'HEURISTICS_IOS_DEPENDENCIES_CARTHAGE_AST'
  );
  assert.equal(
    byId.get('heuristics.ios.security.userdefaults-sensitive-data.ast')?.then.code,
    'HEURISTICS_IOS_SECURITY_USERDEFAULTS_SENSITIVE_DATA_AST'
  );
  assert.equal(
    byId.get('heuristics.ios.security.insecure-transport.ast')?.then.code,
    'HEURISTICS_IOS_SECURITY_INSECURE_TRANSPORT_AST'
  );
  assert.equal(
    byId.get('heuristics.ios.localization.localizable-strings.ast')?.then.code,
    'HEURISTICS_IOS_LOCALIZATION_LOCALIZABLE_STRINGS_AST'
  );
  assert.equal(
    byId.get('heuristics.ios.localization.hardcoded-ui-string.ast')?.then.code,
    'HEURISTICS_IOS_LOCALIZATION_HARDCODED_UI_STRING_AST'
  );
  assert.equal(
    byId.get('heuristics.ios.assets.loose-resource.ast')?.then.code,
    'HEURISTICS_IOS_ASSETS_LOOSE_RESOURCE_AST'
  );
  assert.equal(
    byId.get('heuristics.ios.accessibility.fixed-font-size.ast')?.then.code,
    'HEURISTICS_IOS_ACCESSIBILITY_FIXED_FONT_SIZE_AST'
  );
  assert.equal(
    byId.get('heuristics.ios.localization.physical-text-alignment.ast')?.then.code,
    'HEURISTICS_IOS_LOCALIZATION_PHYSICAL_TEXT_ALIGNMENT_AST'
  );
  assert.equal(
    byId.get('heuristics.ios.performance.blocking-sleep.ast')?.then.code,
    'HEURISTICS_IOS_PERFORMANCE_BLOCKING_SLEEP_AST'
  );
  assert.equal(
    byId.get('heuristics.ios.accessibility.icon-only-control-label.ast')?.then.code,
    'HEURISTICS_IOS_ACCESSIBILITY_ICON_ONLY_CONTROL_LABEL_AST'
  );
  assert.equal(
    byId.get('heuristics.ios.preconcurrency.ast')?.then.code,
    'HEURISTICS_IOS_PRECONCURRENCY_AST'
  );
  assert.equal(
    byId.get('heuristics.ios.nonisolated-unsafe.ast')?.then.code,
    'HEURISTICS_IOS_NONISOLATED_UNSAFE_AST'
  );
  assert.equal(
    byId.get('heuristics.ios.assume-isolated.ast')?.then.code,
    'HEURISTICS_IOS_ASSUME_ISOLATED_AST'
  );
  assert.equal(
    byId.get('heuristics.ios.legacy-swiftui-observable-wrapper.ast')?.then.code,
    'HEURISTICS_IOS_LEGACY_SWIFTUI_OBSERVABLE_WRAPPER_AST'
  );
  assert.equal(
    byId.get('heuristics.ios.passed-value-state-wrapper.ast')?.then.code,
    'HEURISTICS_IOS_PASSED_VALUE_STATE_WRAPPER_AST'
  );
  assert.equal(
    byId.get('heuristics.ios.foreach-indices.ast')?.then.code,
    'HEURISTICS_IOS_FOREACH_INDICES_AST'
  );
  assert.equal(
    byId.get('heuristics.ios.contains-user-filter.ast')?.then.code,
    'HEURISTICS_IOS_CONTAINS_USER_FILTER_AST'
  );
  assert.equal(
    byId.get('heuristics.ios.geometryreader.ast')?.then.code,
    'HEURISTICS_IOS_GEOMETRYREADER_AST'
  );
  assert.equal(
    byId.get('heuristics.ios.font-weight-bold.ast')?.then.code,
    'HEURISTICS_IOS_FONT_WEIGHT_BOLD_AST'
  );
  assert.equal(
    byId.get('heuristics.ios.uiscreen-main-bounds.ast')?.then.code,
    'HEURISTICS_IOS_UISCREEN_MAIN_BOUNDS_AST'
  );
  assert.equal(byId.get('heuristics.ios.foreground-color.ast')?.then.code, 'HEURISTICS_IOS_FOREGROUND_COLOR_AST');
  assert.equal(
    byId.get('heuristics.ios.sheet-is-presented.ast')?.then.code,
    'HEURISTICS_IOS_SHEET_IS_PRESENTED_AST'
  );
  assert.equal(
    byId.get('heuristics.ios.legacy-onchange.ast')?.then.code,
    'HEURISTICS_IOS_LEGACY_ONCHANGE_AST'
  );
  assert.equal(
    byId.get('heuristics.ios.testing.xctassert.ast')?.then.code,
    'HEURISTICS_IOS_TESTING_XCTASSERT_AST'
  );
  assert.equal(
    byId.get('heuristics.ios.testing.xctest-suite-modernizable.ast')?.then.code,
    'HEURISTICS_IOS_TESTING_XCTEST_SUITE_MODERNIZABLE_AST'
  );
  assert.equal(
    byId.get('heuristics.ios.testing.wait-for-expectations.ast')?.then.code,
    'HEURISTICS_IOS_TESTING_WAIT_FOR_EXPECTATIONS_AST'
  );
  assert.equal(
    byId.get('heuristics.ios.testing.legacy-expectation-description.ast')?.then.code,
    'HEURISTICS_IOS_TESTING_LEGACY_EXPECTATION_DESCRIPTION_AST'
  );
  assert.equal(
    byId.get('heuristics.ios.testing.mixed-frameworks.ast')?.then.code,
    'HEURISTICS_IOS_TESTING_MIXED_FRAMEWORKS_AST'
  );
  assert.equal(
    byId.get('heuristics.ios.core-data.nsmanagedobject-async-boundary.ast')?.then.code,
    'HEURISTICS_IOS_CORE_DATA_NSMANAGEDOBJECT_ASYNC_BOUNDARY_AST'
  );
  assert.equal(
    byId.get('heuristics.ios.core-data.layer-leak.ast')?.then.code,
    'HEURISTICS_IOS_CORE_DATA_LAYER_LEAK_AST'
  );
  assert.equal(
    byId.get('heuristics.ios.swiftdata.layer-leak.ast')?.then.code,
    'HEURISTICS_IOS_SWIFTDATA_LAYER_LEAK_AST'
  );
  assert.equal(
    byId.get('heuristics.ios.core-data.nsmanagedobject-state-leak.ast')?.then.code,
    'HEURISTICS_IOS_CORE_DATA_NSMANAGEDOBJECT_STATE_LEAK_AST'
  );

  for (const rule of iosRules) {
    assert.equal(rule.platform, 'ios');
    assert.equal(rule.severity, 'WARN');
    assert.equal(rule.locked, true);
    assert.equal(rule.when.kind, 'Heuristic');
    assert.equal(rule.then.kind, 'Finding');
    assert.equal(rule.when.where?.ruleId, rule.id);
  }
});
