export const DEFAULT_LIST_SEPARATOR = ', ';

export const DEFAULT_MEMORY_SHADOW_CONFIDENCE_BLOCK = 0.9;
export const DEFAULT_MEMORY_SHADOW_CONFIDENCE_WARN = 0.75;
export const DEFAULT_MEMORY_SHADOW_CONFIDENCE_WARN_ADVISORY = 0.7;
export const DEFAULT_MEMORY_SHADOW_CONFIDENCE_ALLOW = 0.65;

export const DEFAULT_DEGRADED_MODE_ACTION_BLOCK = 'block' as const;
export const DEFAULT_DEGRADED_MODE_ACTION_ALLOW = 'allow' as const;

export const DEFAULT_RULES_COVERAGE_RATIO_DECIMALS = 6;
export const DEFAULT_GATE_AUDIT_MODE = 'gate' as const;
