import {
  DEFAULT_DEGRADED_MODE_ACTION_ALLOW,
  DEFAULT_DEGRADED_MODE_ACTION_BLOCK,
  DEFAULT_GATE_AUDIT_MODE,
  DEFAULT_LIST_SEPARATOR,
  DEFAULT_MEMORY_SHADOW_DISPLAY_PRECISION,
  DEFAULT_MEMORY_SHADOW_CONFIDENCE_ALLOW,
  DEFAULT_MEMORY_SHADOW_CONFIDENCE_BLOCK,
  DEFAULT_MEMORY_SHADOW_CONFIDENCE_WARN,
  DEFAULT_MEMORY_SHADOW_CONFIDENCE_WARN_ADVISORY,
  DEFAULT_RULES_COVERAGE_RATIO_DECIMALS,
  LIFECYCLE_GATE_STAGES,
  MAX_IOS_TEST_QUALITY_SAMPLE_FILES,
  MAX_OBSERVED_CODE_PATHS_SAMPLE,
  MAX_SCOPE_SAMPLE_PATHS,
} from './runPlatformGateDefaults';

const parseConfidence = (value: string | undefined, fallback: number): number => {
  const parsed = Number.parseFloat(value ?? '');
  return Number.isFinite(parsed) ? parsed : fallback;
};

export const LIST_SEPARATOR = DEFAULT_LIST_SEPARATOR;

export const MEMORY_SHADOW_CONFIDENCE_BLOCK = parseConfidence(
  process.env.PUMUKI_MEMORY_SHADOW_CONFIDENCE_BLOCK,
  DEFAULT_MEMORY_SHADOW_CONFIDENCE_BLOCK
);
export const MEMORY_SHADOW_CONFIDENCE_WARN = parseConfidence(
  process.env.PUMUKI_MEMORY_SHADOW_CONFIDENCE_WARN,
  DEFAULT_MEMORY_SHADOW_CONFIDENCE_WARN
);
export const MEMORY_SHADOW_CONFIDENCE_WARN_ADVISORY = parseConfidence(
  process.env.PUMUKI_MEMORY_SHADOW_CONFIDENCE_WARN_ADVISORY,
  DEFAULT_MEMORY_SHADOW_CONFIDENCE_WARN_ADVISORY
);
export const MEMORY_SHADOW_CONFIDENCE_ALLOW = parseConfidence(
  process.env.PUMUKI_MEMORY_SHADOW_CONFIDENCE_ALLOW,
  DEFAULT_MEMORY_SHADOW_CONFIDENCE_ALLOW
);

export const DEGRADED_MODE_ACTION_BLOCK =
  process.env.PUMUKI_DEGRADED_MODE_ACTION_BLOCK?.trim() || DEFAULT_DEGRADED_MODE_ACTION_BLOCK;
export const DEGRADED_MODE_ACTION_ALLOW =
  process.env.PUMUKI_DEGRADED_MODE_ACTION_ALLOW?.trim() || DEFAULT_DEGRADED_MODE_ACTION_ALLOW;

export {
  DEFAULT_GATE_AUDIT_MODE,
  DEFAULT_MEMORY_SHADOW_DISPLAY_PRECISION,
  DEFAULT_RULES_COVERAGE_RATIO_DECIMALS,
  LIFECYCLE_GATE_STAGES,
  MAX_IOS_TEST_QUALITY_SAMPLE_FILES,
  MAX_OBSERVED_CODE_PATHS_SAMPLE,
  MAX_SCOPE_SAMPLE_PATHS,
};
