import {
  DEFAULT_CONSUMER_SUPPORT_TICKET_AUTH_REPORT_FILE,
  DEFAULT_CONSUMER_SUPPORT_TICKET_OUT_FILE,
  DEFAULT_CONSUMER_SUPPORT_TICKET_REPO,
  DEFAULT_CONSUMER_SUPPORT_TICKET_SUPPORT_BUNDLE_FILE,
  type ConsumerSupportTicketCliOptions,
} from './consumer-support-ticket-cli-contract';

export const createConsumerSupportTicketDefaultOptions = (): ConsumerSupportTicketCliOptions => ({
  repo: DEFAULT_CONSUMER_SUPPORT_TICKET_REPO,
  supportBundleFile: DEFAULT_CONSUMER_SUPPORT_TICKET_SUPPORT_BUNDLE_FILE,
  authReportFile: DEFAULT_CONSUMER_SUPPORT_TICKET_AUTH_REPORT_FILE,
  outFile: DEFAULT_CONSUMER_SUPPORT_TICKET_OUT_FILE,
});
