import {
  DEFAULT_CONSUMER_STARTUP_UNBLOCK_AUTH_REPORT_FILE,
  DEFAULT_CONSUMER_STARTUP_UNBLOCK_OUT_FILE,
  DEFAULT_CONSUMER_STARTUP_UNBLOCK_REPO,
  DEFAULT_CONSUMER_STARTUP_UNBLOCK_SUPPORT_BUNDLE_FILE,
  DEFAULT_CONSUMER_STARTUP_UNBLOCK_WORKFLOW_LINT_FILE,
  type ConsumerStartupUnblockCliOptions,
} from './consumer-startup-unblock-args-contract';

export const createConsumerStartupUnblockDefaultOptions =
  (): ConsumerStartupUnblockCliOptions => ({
    repo: DEFAULT_CONSUMER_STARTUP_UNBLOCK_REPO,
    supportBundleFile: DEFAULT_CONSUMER_STARTUP_UNBLOCK_SUPPORT_BUNDLE_FILE,
    authReportFile: DEFAULT_CONSUMER_STARTUP_UNBLOCK_AUTH_REPORT_FILE,
    workflowLintReportFile: DEFAULT_CONSUMER_STARTUP_UNBLOCK_WORKFLOW_LINT_FILE,
    outFile: DEFAULT_CONSUMER_STARTUP_UNBLOCK_OUT_FILE,
  });
