export const ADVANCED_MENU_HELP: Readonly<Record<string, string>> = {
  '1': 'Evalua solo los cambios staged (PRE_COMMIT).',
  '2': 'Evalua upstream..HEAD (PRE_PUSH).',
  '3': 'Evalua baseRef..HEAD (CI).',
  '28': 'Auditoria legacy/read-only: snapshot completo del repo (HEAD) con policy PRE_COMMIT.',
  '29': 'Auditoria legacy/read-only: snapshot indexado (repo + staged) con policy PRE_COMMIT.',
  '30': 'Auditoria legacy/read-only: cambios staged + unstaged del working tree con policy PRE_COMMIT.',
  '4': 'Ejecuta gate de iOS en modo CI.',
  '5': 'Ejecuta gate de backend en modo CI.',
  '6': 'Ejecuta gate de frontend en modo CI.',
  '7': 'Muestra bundles activos de skills con version y hash.',
  '8': 'Lee el .ai_evidence.json actual.',
  '9': 'Genera reporte de estado de sesion del adapter.',
  '10': 'Recolecta artefactos CI del consumidor.',
  '11': 'Genera reporte de auth/check de CI del consumidor.',
  '12': 'Ejecuta lint de workflows del consumidor.',
  '13': 'Toolkit soporte: genera support bundle de startup-failure.',
  '14': 'Toolkit soporte: genera borrador de ticket de soporte.',
  '15': 'Toolkit soporte: genera reporte de startup-unblock status.',
  '16': 'Genera reporte real-session del adapter.',
  '17': 'Verifica freshness de skills lock.',
  '18': 'Configura hard mode/enforcement enterprise.',
  '31': 'Configura notificaciones del sistema (macOS) para eventos criticos.',
  '32': 'Auditoria legacy/read-only: cobertura de reglas evaluadas por stage.',
  '33': 'Importa reglas custom desde AGENTS.md/SKILLS.md hacia .pumuki/custom-rules.json.',
  '19': 'Toolkit soporte: ejecuta startup triage bundle del consumidor.',
  '20': 'Toolkit soporte: genera reporte A/B del mock consumer.',
  '21': 'Toolkit soporte: genera reporte de blockers readiness (phase5).',
  '22': 'Toolkit soporte: genera adapter readiness report.',
  '23': 'Toolkit soporte: genera execution closure status (phase5).',
  '24': 'Toolkit soporte: ejecuta cierre phase5 one-shot.',
  '25': 'Toolkit legacy: genera external handoff report (phase5).',
  '26': 'Toolkit soporte: limpia artefactos locales de validacion.',
  '27': 'Salir.',
};

export const compactAdvancedMenuHelp = (optionId: string): string => {
  return (ADVANCED_MENU_HELP[optionId] ?? '').trim().replace(/\.$/, '');
};
