import type { LegacyAuditSummary } from './framework-menu-legacy-audit-types';
import {
  LEGACY_AUDIT_OVERVIEW_SUBTITLE,
  LEGACY_AUDIT_OVERVIEW_TITLE,
  renderLegacyPanel,
} from './framework-menu-legacy-audit-render-panel';
import {
  formatLegacyAstBreakdown,
  formatLegacyEslintAudit,
  formatLegacyFileDiagnostics,
  formatLegacyPatternChecks,
  formatLegacyRulesetBreakdown,
  formatLegacyStatusLine,
} from './framework-menu-legacy-audit-render-sections';

const codeHealthLabel = (score: number): string => {
  if (score >= 80) {
    return 'Good';
  }
  if (score >= 60) {
    return 'Moderate';
  }
  return 'Needs attention';
};

const buildOverviewPanelLines = (): string[] => {
  return [
    LEGACY_AUDIT_OVERVIEW_TITLE,
    LEGACY_AUDIT_OVERVIEW_SUBTITLE,
    '',
    '1) Pattern checks',
    '2) ESLint audits',
    '3) AST Intelligence analysis',
    '4) Intelligent Audit Gate (block/allow)',
    '5) Evidence update (.AI_EVIDENCE.json)',
    '',
    'Pipeline',
    'Source files → AST analyzers → violations → severity evaluation → AI Gate verdict',
    '',
    'Outputs',
    '• .audit_tmp/ast-summary.json',
    '• .audit_tmp/ast-summary-enhanced.json',
    '• reports/ (json + text)',
    '• .AI_EVIDENCE.json (ai_gate + metrics)',
    '',
    'Rule: Fail fast, block early',
    'Goal: deterministic governance across iOS / Android / Backend / Frontend',
  ];
};

const buildQuickSummaryPanelLines = (summary: LegacyAuditSummary): string[] => {
  return [
    'QUICK SUMMARY',
    '',
    `Files scanned: ${summary.filesScanned}`,
    `Files affected: ${summary.filesAffected}`,
    `Total violations: ${summary.totalViolations}`,
    `ESLint errors: ${summary.eslint.errors}`,
    `Critical issues: ${summary.bySeverity.CRITICAL}`,
    `High priority: ${summary.bySeverity.HIGH}`,
    '',
    ...formatLegacyStatusLine(summary).split('\n'),
    '',
    ...formatLegacyPatternChecks(summary).split('\n'),
    '',
    ...formatLegacyEslintAudit(summary).split('\n'),
  ];
};

const buildRemediationPanelLines = (summary: LegacyAuditSummary): string[] => {
  const topViolations = summary.topViolations.length === 0
    ? ['• none']
    : summary.topViolations.flatMap((violation) => [
      `• ${violation.ruleId} (${violation.count} violations)`,
      '  → Review and fix violations.',
    ]);
  const topFindings = summary.topFindings ?? [];
  const topFindingLocations = topFindings.length === 0
    ? ['• none']
    : topFindings.map((finding) => (
      `• [${finding.severity}] ${finding.ruleId} → ${finding.file}:${finding.line}`
    ));

  return [
    '5) TOP VIOLATIONS & REMEDIATION',
    '',
    ...topViolations,
    '',
    'Clickable locations (file:line)',
    ...topFindingLocations,
    '',
    '6) EXECUTIVE SUMMARY',
  ];
};

const buildMetricsPanelLines = (summary: LegacyAuditSummary): string[] => {
  const commitStatus = summary.bySeverity.CRITICAL > 0 || summary.bySeverity.HIGH > 0
    ? 'COMMIT BLOCKED — STRICT REPO+STAGING'
    : 'COMMIT ALLOWED';
  const blockedMessage = summary.bySeverity.CRITICAL > 0 || summary.bySeverity.HIGH > 0
    ? 'ACTION REQUIRED: Critical or high-severity issues detected. Please review and fix before proceeding.'
    : 'No blocking violations detected.';
  const actionLine = commitStatus.includes('BLOCKED')
    ? 'Action: clean entire repository before committing.'
    : 'Action: proceed with commit flow.';
  const affectedRatio = summary.filesScanned > 0
    ? Math.round((summary.filesAffected / Math.max(1, summary.filesScanned)) * 100)
    : 0;
  const nextAction = commitStatus.includes('BLOCKED')
    ? 'Next action: fix CRITICAL/HIGH findings and rerun full audit.'
    : summary.bySeverity.MEDIUM > 0 || summary.bySeverity.LOW > 0
      ? 'Next action: schedule MEDIUM/LOW cleanup without blocking delivery.'
      : 'Next action: maintain baseline and continue with regular checks.';

  return [
    'METRICS',
    `Total violations detected: ${summary.totalViolations}`,
    `ESLint errors: ${summary.eslint.errors}`,
    `Critical issues: ${summary.bySeverity.CRITICAL}`,
    `High priority issues: ${summary.bySeverity.HIGH}`,
    `Files scanned: ${summary.filesScanned}`,
    `Affected ratio: ${affectedRatio}%`,
    '',
    `Code Health Score: ${summary.codeHealthScore}% (${codeHealthLabel(summary.codeHealthScore)})`,
    '',
    blockedMessage,
    nextAction,
    '',
    'FINAL SUMMARY — VIOLATIONS BY SEVERITY',
    `● CRITICAL: ${summary.bySeverity.CRITICAL}`,
    `● HIGH: ${summary.bySeverity.HIGH}`,
    `● MEDIUM: ${summary.bySeverity.MEDIUM}`,
    `● LOW: ${summary.bySeverity.LOW}`,
    '',
    commitStatus,
    actionLine,
    `Stage: ${summary.stage} • Outcome: ${summary.outcome}`,
    'Generated by Pumuki — Hook-System',
  ];
};

export const formatLegacyAuditReport = (
  summary: LegacyAuditSummary,
  options?: { panelWidth?: number; color?: boolean }
): string => {
  if (summary.status === 'missing') {
    return 'No .ai_evidence.json found. Run an audit option first.';
  }
  if (summary.status === 'invalid') {
    return '.ai_evidence.json is invalid. Regenerate evidence and retry.';
  }

  const widthOptions = { width: options?.panelWidth, color: options?.color };
  return [
    renderLegacyPanel(buildOverviewPanelLines(), widthOptions),
    renderLegacyPanel(buildQuickSummaryPanelLines(summary), widthOptions),
    renderLegacyPanel(formatLegacyAstBreakdown(summary).split('\n'), widthOptions),
    renderLegacyPanel(formatLegacyRulesetBreakdown(summary).split('\n'), widthOptions),
    renderLegacyPanel(buildRemediationPanelLines(summary), widthOptions),
    renderLegacyPanel(buildMetricsPanelLines(summary), widthOptions),
  ].join('\n\n');
};
