import {
  DEFAULT_MOCK_CONSUMER_AB_BLOCK_EVIDENCE_FILE,
  DEFAULT_MOCK_CONSUMER_AB_BLOCK_SUMMARY,
  DEFAULT_MOCK_CONSUMER_AB_MINIMAL_EVIDENCE_FILE,
  DEFAULT_MOCK_CONSUMER_AB_MINIMAL_SUMMARY,
  DEFAULT_MOCK_CONSUMER_AB_OUT_FILE,
  DEFAULT_MOCK_CONSUMER_AB_REPO,
  type MockConsumerAbCliOptions,
} from './mock-consumer-ab-contract';

export const createMockConsumerAbDefaultCliOptions = (): MockConsumerAbCliOptions => ({
  repo: DEFAULT_MOCK_CONSUMER_AB_REPO,
  outFile: DEFAULT_MOCK_CONSUMER_AB_OUT_FILE,
  blockSummaryFile: DEFAULT_MOCK_CONSUMER_AB_BLOCK_SUMMARY,
  minimalSummaryFile: DEFAULT_MOCK_CONSUMER_AB_MINIMAL_SUMMARY,
  blockEvidenceFile: DEFAULT_MOCK_CONSUMER_AB_BLOCK_EVIDENCE_FILE,
  minimalEvidenceFile: DEFAULT_MOCK_CONSUMER_AB_MINIMAL_EVIDENCE_FILE,
  dryRun: false,
});
